### ISSUE TITLE
Fetch does not start without Lezhin disclaimer image

### ISSUE THREAD

**Issue by myr-onl** [diomirox/mdownload#7]
Extension works amazing, but wanted to report this behavior in case others can reproduce. When I go to get images for chapters/content that do not begin with 'This LEZHIN comic is protected..." image, the fetch process doesn't start and I can't get any of the images.

Here's a free chapter I wasn't able to get images for: https://www.lezhinus.com/en/comic/loveillusion/e2 (sorry to incidentally post my cringe). It was mostly bonus content like this I couldn't export, but I wasn't able to get an actual chapter from the same series for seemingly the same reason.

Let me know if you need more info or if I can be of any help figuring this one out.

**Comment by diomirox** [comment]
Check out the new version at https://github.com/diomirox/mdownload/releases/tag/v0.2.0. If you encounter any issues, please don't hesitate to report them.

**Comment by myr-onl** [comment]
Thanks so much - I was able to grab that one chapter. I also love the new subfolders/numbering for the chapters!
