### ISSUE TITLE
Downloader not working due to website update.

### ISSUE THREAD

**Issue by yimeji** [diomirox/mdownload#8]
They updated the website and the downloader no longer working.

**Comment by diomirox** [comment]
It seems I decode every image. Some images do not need to be decoded.  I guess It will be fixed on the next release.

**Comment by diomirox** [comment]
Check out the new version at https://github.com/diomirox/mdownload/releases/tag/v0.2.0. If you encounter any issues, please don't hesitate to report them.

**Comment by diomirox** [comment]
I guess this issue may be fixed. Is there still a problem you can reopen this issue. Thank you.
